### ISSUE TITLE
Get "Admins" to work properly

### ISSUE THREAD

**Issue by mikezimm** [mikezimm/pivottiles7#46] opened 2020-12-14 16:16 UTC
Problem documented here:
https://github.com/pnp/pnpjs/issues/1480

Basically IsSiteAdmin is not returned correctly unless you are site admin.

If the issue can't be resolved on the PnpJS Library side, then I will need to add a way to store it in the webpart for later use.

**Comment by koltyakov** [comment] 2020-12-14 16:22
This can't be solved on PnPjs's side, as this doesn't seem any sort of issue in the library, but the API behavior. Not sure was it by design though.

**Comment by koltyakov** [comment] 2020-12-15 10:38
Checked in SPO and SP2016, the hardest part was finding a user with limited permissions. This works in all environment for admin and non-admin and read-only users:

```typescript
sp.web.siteUserInfoList.items.filter(`IsSiteAdmin eq 1`).get().then(console.log);
```

There is no issue in REST API or PnPjs regarding the question, all works as expected.

**Closed** 2020-12-17 21:22 UTC
